### ISSUE TITLE
easy docker setup link broken

### ISSUE THREAD

**Issue by CatspersCoffee** [FuelLabs/bridge-integration-tests#5]
Is there a current docker image available for "full development stack complete with an Ethereum client and Fuel client" available or is this getting re-spun? link broken {https://github.com/FuelLabs/bridge-integration-tests/blob/_fuel_dev_environment}

thanks!

**Comment by pixelcircuits** [comment]
Sorry, it's the `_fuel_dev_environment` folder in the repo. https://github.com/FuelLabs/bridge-integration-tests/tree/master/_fuel_dev_environment

**Comment by CatspersCoffee** [comment]
Thanks!
